#!/bin/bash

# Usage: ./configure [OPTION]... [VAR=VALUE]...

# To assign environment variables (e.g., CC, CFLAGS...), specify them as
# VAR=VALUE.  See below for descriptions of some of the useful variables.

# Optional Packages:
#   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
#   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
#   --with-mysql            compile with MySQL support (default is enabled)
#   --with-pgsql            compile with PostgreSQL support (default is
#                           disabled)
#   --with-pgsql-includes   path to PostgreSQL header files
#   --with-pgsql-libs       path to PostgreSQL libraries

# Some influential environment variables:
#   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
#               nonstandard directory <lib dir>
#   LIBS        libraries to pass to the linker, e.g. -l<library>
#   CPPFLAGS    C/C++/Objective C preprocessor flags, e.g. -I<include dir> if
#               you have headers in a nonstandard directory <include dir>

# Use these variables to override the choices made by `configure' or to help
# it to find libraries and programs with nonstandard names/locations.