#!/bin/bash

#
# Copyright (c) 2014,  Regents of the Columbia University 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


# variables
APP_DIR=$COLO/apps/pgsql


# change diretory and start server
cd $APP_DIR/${1}/install
bin/pg_ctl start -D $APP_DIR/${1}/install/data
sleep 2


# test

# createdb creates a PostgreSQL database.
# Usage:
#   createdb [OPTION]... [DBNAME] [DESCRIPTION]
# Options:
#   -O, --owner=OWNER            database user to own the new database
bin/createdb -O root dbtest

# pgbench [OPTION]... [DBNAME]
# Initialization options:
#   -i           invokes initialization mode
# Benchmarking options:
#   -c NUM       number of concurrent database clients
#   -j NUM       number of threads
#   -t NUM       number of transactions each client runs
# Common options:
#   -h HOSTNAME    database server host or socket directory
#   -p PORT        database server port number
#   -U USERNAME    connect as specified database user

# Before we start the benchmark, we have to initialize the database,
# which can be done by using the -i flag.
bin/pgbench -i -U root dbtest -h 127.0.0.1 -p 5452 -j 10 -c 20
# Perform a test:
bin/pgbench -U root dbtest -h 127.0.0.1 -p 5452 -j 10 -c 20 -t 100

bin/dropdb dbtest


# stop server
bin/pg_ctl stop -D $APP_DIR/${1}/install/data

