#!/bin/bash

if [ ! $1 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

if [ ! $2 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

NT=8
cd $COLO/apps/mediatomb

# Note: the -m $PWD option is for setting up the server with the
# config database COLO/apps/mediatomb/.mediatomb

ab -n $NT -c $NT \
http://$1:$2/content/media/object_id/8/res_id/none/pr_name/vlcmpeg/tr/1

# Usage: ab [options] [http[s]://]hostname[:port]/path
# Options are:
#     -n requests     Number of requests to perform
#     -c concurrency  Number of multiple requests to make at a time
