#!/bin/bash

if [ ! $1 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

if [ ! $2 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

NT=8
cd $COLO/apps/mediatomb

# Note: the -m $PWD option is for setting up the server with the
# config database COLO/apps/mediatomb/.mediatomb

# Fetch the original stream:
# wget http://<ip>:<port>/content/media/object_id/<object_id>/res_id/0
# The object_id can be found by browsing to an AVI file via the MediaTomb
# Web UI and placing your mouse cursor over the file. Your web browser
# should display the URL of the file which will contain the object_id.

# Fetch the transcoded stream:
# wget http://<ip>:<port>/content/media/object_id/<object_id>/res_id/none/pr_name/<profile_name>/tr/1

ab -n $NT -c $NT \
http://$1:$2/content/media/object_id/8/res_id/none/pr_name/vlcmpeg/tr/1

# Usage: ab [options] [http[s]://]hostname[:port]/path
# Options are:
#     -n requests     Number of requests to perform
#     -c concurrency  Number of multiple requests to make at a time
