#!/bin/bash

if [ ! $1 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

if [ ! $2 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi


cd $COLO/apps/mediatomb
#killall -9 mediatomb server.out wget mencoder ab &> /dev/null
#sleep 1
#killall -9 mediatomb server.out wget mencoder ab &> /dev/null
rm -rf .db

# Note: the -m $PWD option is for setting up the server with the
# config database COLO/apps/mediatomb/.mediatomb

./install/bin/mediatomb -i $1 -p $2 -m $PWD &> out.txt &
sleep 5
