#!/bin/bash

if [ ! $1 ];
then
        echo "Usage: $0 <server IP> <server port>"
	echo "$0 127.0.0.1 7000"
        exit 1;
fi

if [ ! $2 ];
then
        echo "Usage: $0 <server IP> <server port>"
        echo "$0 127.0.0.1 7000"
        exit 1;
fi

NUM_REQ=8
NUM_T=8

cd $COLO/apps/mongoose

$COLO/apps/apache/install/bin/ab -n $NUM_REQ -c $NUM_T http://$1:$2/test.php # GET request
# Non-2xx responses may indicate some problem

# $COLO/apps/apache/install/bin/ab -n $NUM_REQ -c $NUM_T http://$1:$2/index.html # Apache may cache the file